const passport = require('passport');

const mongoose = require('mongoose');
const GoogleStrategy = require('passport-google-oauth20').Strategy;
const keys = require('../config/keys');
const User = mongoose.model('users');

passport.serializeUser((user,done) => {
  done(null, user.id); //incase of multiple auths like fb or linkedin we cannot always use the googleid for checking in adb we have to use the id autogenerated by mongodb

});
//user.id is the shortcut for mongodb auto generated id

passport.deserializeUser((id,done) => { 
  User.findById(id)
  .then(user => {
    done(null,user);
  });

});

passport.use(new GoogleStrategy({
    clientID : keys.googleClientID,
    clientSecret : keys.googleClientSecret,
    callbackURL : '/auth/google/callback'
},
(accessToken,refreshToken,profile,done) => {
  User.findOne({ googleId : profile.id }).then((existingUser)=> {
        if(existingUser)
        {
          //we already have a record with this id
          done(null, existingUser);
        }
        else
        {
          //the user is new, add the user to the database
          new User({
            googleId : profile.id,
            googleName: profile.displayName,
          })
          .save()
          .then(user => done(null,user));
        }
      })
    }
));


